### ISSUE TITLE
IoT-Dashboard

### ISSUE THREAD

**Issue by sebastianhaberlNW** [Trawacho/StockTV#8]
Hallo, ich habe Probleme bei der Installation nach der beiliegenden Anleitung.
Genauer: Ich weis nicht wie ich ein IoT-Dashboard auf meinen PC installieren kann... die einzigen sinnvollen links welche ich im Web dazu finde würden das Win10 IoT Core Dashboard installieren... diese verlaufen allerdings alle ins leere!

Gibt es da evtl. eine Lösung?

vielen Dank im Voraus!

Mit freundlichen Grüßen
Sebastian

**Comment by Trawacho** [comment]
MS hat das Produkt leider eingestellt. [Hier](https://github.com/Trawacho/StockTV/tree/master/iotdb) liegt eine ZIP-Datei mit dem IoT-Dashboard, dass du mal versuchen kannst.

**Comment by sebastianhaberlNW** [comment]
Hallo, danke für die schnelle Hilfe!

Das hat alles soweit funktioniert...

Allerdings ist bei der Installation der App folgender Fehler aufgetreten...

Installation Failed
Failure reason: Windows cannot install package StockTV_1.5.0.0_arm__k2g2k3q01jb7p because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or ARM processor architecture and minimum version 14.0.30704.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.26706.0_arm__8wekyb3d8bbwe} Failure text: Package failed updates, dependency or conflict validation. (0x80073cf3)

Meines Erachtens sollte das doch mit den Windows-Updates mitkommen... 
Da diese bei erneutem "Check for Updates" alle auf dem neusten Stand sind, bin ich wieder mal ratlos....

Kannst du mir da evtl. nochmal weiterhelfen bitte?

**Comment by bachmichl** [comment]
hast zu zur installation der app auch die dependencies installiert - siehe punkt 2 in der installationsbeschreibung? dort sollte das framework dabei sein. bei der installation musst du das app-bundle und die 3 bundles aus den dependencies auswählen.

**Comment by bachmichl** [comment]
1.5.0.0 ist nicht der letzte stand und wird mit der letzten/aktuellen stockapp nicht funktionieren.

**Comment by sebastianhaberlNW** [comment]
![2024-11-15 16_24_21-TelemetryDependencies – Datei-Explorer](https://github.com/user-attachments/assets/244fb7b3-a83d-464b-abcb-8f095b201e91)

Ich dachte ja, unter dependencies sind bei mir diese Dateien enthalten... die hätte ich alle mit installiert

**Comment by bachmichl** [comment]
lade doch noch einmal die stocktv 1.6 runter. 1.5 ist eh veraltet

**Comment by sebastianhaberlNW** [comment]
Habe ich bereits gemacht, ist bei beiden der fall

![image](https://github.com/user-attachments/assets/e832912d-6542-43f7-ac07-b13c67235665)

Der Ordner fehlt hier auch...

**Comment by bachmichl** [comment]
hab es soeben versucht. bei mir ist er da. ich kann die 3 files auch nicht anhängen. email? sind 16mb

**Comment by bachmichl** [comment]
[dependencies.zip](https://github.com/user-attachments/files/17777887/dependencies.zip)

**Comment by bachmichl** [comment]
vielleicht klappts

**Comment by Trawacho** [comment]
@sebastianhaberlNW du darfst nicht die Daten aus dem AppPackages Ordner nehmen. Sondern du musst bei den Releases schauen!

**Comment by sebastianhaberlNW** [comment]
Alles klar, 
hat geklappt!

DANKE!
